version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    volumes:
        - .:/app
    environment:
      HDRCRYPTO_ADDRESS: ":3000"
    ports:
      - "3000:3000"